// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl4nOpQ474DGMmw-Izcj2ZJcOphE0DoBA',
    appId: '1:842588292911:web:05d884c24e54b5e8f6c3da',
    messagingSenderId: '842588292911',
    projectId: 'testing-8cb6f',
    authDomain: 'testing-8cb6f.firebaseapp.com',
    storageBucket: 'testing-8cb6f.firebasestorage.app',
    measurementId: 'G-23RNCK7H0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iQpKFwDFnuOsvF8EC4BSM-dy_GuFEFk',
    appId: '1:842588292911:android:e4f98de3c328089cf6c3da',
    messagingSenderId: '842588292911',
    projectId: 'testing-8cb6f',
    storageBucket: 'testing-8cb6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIHGjUKywZclcDHVSLtRzN6Bj_Yf578fQ',
    appId: '1:842588292911:ios:87fafd706aa80abff6c3da',
    messagingSenderId: '842588292911',
    projectId: 'testing-8cb6f',
    storageBucket: 'testing-8cb6f.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIHGjUKywZclcDHVSLtRzN6Bj_Yf578fQ',
    appId: '1:842588292911:ios:87fafd706aa80abff6c3da',
    messagingSenderId: '842588292911',
    projectId: 'testing-8cb6f',
    storageBucket: 'testing-8cb6f.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl4nOpQ474DGMmw-Izcj2ZJcOphE0DoBA',
    appId: '1:842588292911:web:1566b581771be701f6c3da',
    messagingSenderId: '842588292911',
    projectId: 'testing-8cb6f',
    authDomain: 'testing-8cb6f.firebaseapp.com',
    storageBucket: 'testing-8cb6f.firebasestorage.app',
    measurementId: 'G-VNML4TSTVE',
  );

}